sudo: false
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby

before_install:
  - gem install bundler

script:
  - bundle exec rspec --order random --format documentation

matrix:
  allow_failures:
    rvm:
      - ruby-head
